import "@/styles/globals.css";

import type { Metadata } from "next";

import { jua } from "@/public/fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jua.className} antialiased`}>{children}</body>
    </html>
  );
}
